# creds depends upon the env refer to default schema public
# it's an internal service of  dataos which is not exposed publicly so can not be connected with any gui applications
version: v1
name: postgres-read-write01
type: workflow
tags:
  - bq
  - dataset
description: This job read and write data from to postgres
title: Read Write Postgres
workflow:
  dag:
    - name: write-postgres
      title: Write Postgres
      description: This job write data from postgres
      spec:
        tags:
          - Connect
        stack: flare:5.0
        compute: runnable-default

        flare:
          job:
            explain: true
            inputs:
              - name: input
                dataset: dataos://icebase:retail/product
                format: Iceberg
              #  schemaPath: dataos://thirdparty01:none/schemas/avsc/city.avsc
            logLevel: INFO
            outputs:
              - name: finalDf
                dataset: dataos://productdb:public/product_data?acl=rw
                driver: org.postgresql.Driver
                format: jdbc
                options:
                  saveMode: overwrite
                description: Data set from Icebase
                tags:
                  - Connect
                title: Postgres Dataset
            steps:
             - sequence: 
                 - name: finalDf
                   sql: |
                      SELECT 
                        product_id,
                        product_name ,
                        product_description ,
                        list_price ,
                        sale_price ,
                        brand_name ,
                        size_name ,
                        size_description ,
                        department_name ,
                        category_name 
                      FROM input
                      LIMIT 1000
