version: v1
name: ${resource-name}
type: ${resource-type}
service:
  title: ${workflow-alerts}
  replicas: 1
  stack: container
  compute: runnable-default
  resources:
    requests:
      cpu: 100m
      memory: 500m
    limits:
      cpu: 1
      memory: 1Gi
  dataosSecrets:           # Referencing the Secret
    - name: ${secret-name}
      workspace: public
      keys: 
        - ${MSTEAM_WEBHOOK_URL}
        - ${DATAOS_API_TOKEN}
        - ${DATAOS_ENV_LINK}
        - ${DATAOS_PULSAR_TOPIC_SUB_ID}

  stackSpec:
    image: labs/ls_workflow_alerts:2.0
    imagePullSecret: modern-docker-secret
    command:
      - python
    arguments:
      - -u
      - ./wf-failed-alerts.py
