pipelines:
  default:
    - step:
        name: Deploy to Azure Blob
        image: microsoft/azure-cli
        script:
          - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          - az storage blob upload-batch --destination $BLOB_CONTAINER_NAME --source . --pattern "**/*.*"  --account-name $AZURE_STORAGE_ACCOUNT_NAME --sas-token $AZURE_STORAGE_SAS_TOKEN --overwrite true