pipelines:
  default:
    - step:
        script:
          - pipe: atlassian/azure-storage-deploy:1.0.2
            variables:
              SOURCE: .
              DESTINATION: 'https://tmdcindiaweb.z13.web.core.windows.net/\\\$web'
              DESTINATION_SAS_TOKEN: $SAS_TOKEN