image: mcr.microsoft.com/azure-cli

pipelines:
  tags:
    '*[0-9].*[0-9].*[0-9]-*':
    - step:
        name: dev-release 
        services:
          - docker
        size: 2x
        caches:
          - docker
        script:
          - export DOCKER_BUILDKIT=1
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker build --progress auto --output site -t moderndocs/moderndocs:latest -f ./docker/Dockerfile .
          - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
          - az storage blob upload-batch --account-name $STORAGE_ACCOUNT_NAME --auth-mode key  --destination '$web' --source $SOURCE_DIR --overwrite
          - az storage blob upload-batch --account-name $STORAGE_ACCOUNT_NAME --auth-mode key  --destination $VERSION_CONTAINER/$BITBUCKET_TAG --source $SOURCE_DIR --overwrite
          - az cdn endpoint purge --resource-group $RESOURCE_GROUP --name $CDN_NAME --profile-name $CDN_NAME --content-paths "/*"
    '*[0-9].*[0-9].*[0-9]':
    - step:
        name: public-release
        services:
          - docker
        size: 2x
        caches:
          - docker
        script:
          - export DOCKER_BUILDKIT=1
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker build --progress auto --output site -t moderndocs/moderndocs:latest -f ./docker/Dockerfile .
          - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
          - az storage blob upload-batch --account-name $STORAGE_ACCOUNT_NAME --auth-mode key  --destination '$web' --source $SOURCE_DIR --overwrite
          - az storage blob upload-batch --account-name $STORAGE_ACCOUNT_NAME --auth-mode key  --destination $VERSION_CONTAINER/$BITBUCKET_TAG --source $SOURCE_DIR --overwrite
          - az cdn endpoint purge --resource-group $RESOURCE_GROUP --name $CDN_NAME --profile-name $CDN_NAME --content-paths "/*"
definitions:
  services:
    docker:
      memory: 4096