pipelines:
  tags:
    '*[0-9].*[0-9].*[0-9]-*':
    - step:
        name: Deploy App
        services:
          - docker
        script:
        - export DOCKER_BUILDKIT=1
        - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
        - docker build --progress auto --output site -t moderndocs/moderndocs:latest -f ./docker/Dockerfile .
        - chmod -R 777 $BITBUCKET_CLONE_DIR
        - pipe: microsoft/azure-storage-deploy:2.0.1
          variables:
            SOURCE: './site/*'
            DESTINATION: 'https://mockdataos.blob.core.windows.net/\\\$web'
            DESTINATION_SAS_TOKEN: $SAS_TOKEN
            EXTRA_ARGS: '--from-to localBlob --recursive'
        artifacts:
          - site/**
    - step:
        name: Save TAG
        script:
        - export DOCKER_BUILDKIT=1
        - pipe: microsoft/azure-storage-deploy:2.0.1
          variables:
            SOURCE: 'site/**'
            DESTINATION: 'https://mockdataos.blob.core.windows.net/moderndocs-versions/$BITBUCKET_TAG'
            DESTINATION_SAS_TOKEN: $SAS_TOKEN
            EXTRA_ARGS: '--from-to localBlob --recursive' 