version: "3"

x-docs-environment: &docs-environment
  APP__SESSION_STORE: "redis://redis:6379/3"
  APP__CACHE_STORE: "redis://redis:6379/3"

services:
  redis:
    image: rubiklabs/redis:6.0.6-g2.2.6
    restart: unless-stopped
    environment: 
      <<: *docs-environment
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL"
    volumes:
      - './docker/redis-config.conf:/opt/bitnami/redis/etc/redis.conf'      

  docs:
    image: rubiklabs/modern-docs:${VERSION:-latest}
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ./local.env
    environment:
      <<: *docs-environment
      APP__LOG_LEVEL: info
    depends_on: 
      - redis
