#### DO NOT CHANGE ####
site_name: DataOS Documentation
copyright: Copyright ⓒ 2023 The Modern Data Company
theme:
    name: material
    custom_dir: overrides
    language: en
    features:
        - navigation.footer
        - navigation.indexes
        - navigation.tabs
        - navigation.sections
        - navigation.instant
        - navigation.top
        - navigation.tracking
        - toc.follow
        # - toc.integrate
    logo: assets/light-modern-logo.png
    favicon: assets/favicon.ico
    font:
        text: Roboto
        code: Roboto Mono
    palette:
      - scheme: default
        primary: blue-grey
        accent: blue-grey
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
      - scheme: slate
        primary: grey
        accent: grey
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
plugins:
    - mermaid2
    - search
    # - mkdocs-versioning:
    #     version: v0.2
extra:
  generator: true
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/themoderndatacompany
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheModernDataCo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/themoderndatacompany
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
#   - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 10
      separator: "-"
  - attr_list
  - md_in_html

#### Update for navigation tabs/options ####      
nav:
    - Home: index.md

    - Resources:
         - Introduction: resources.md
         - Workspace-level Primitives:
             - Cluster: resources/cluster.md
             - Secret: resources/secret.md
             - Service: resources/service.md
             - Stacks:
                 - Introduction: resources/stacks.md
                 - Airbyte: resources/stacks/airbyte.md
                 - Alpha: resources/stacks/alpha.md
                 - Beacon: resources/stacks/beacon.md
                 - Benthos: resources/stacks/benthos.md
                 - Data Toolbox: resources/stacks/data_toolbox.md
                 - Flare: resources/stacks/flare.md
                 - Scanner: resources/stacks/scanner.md
             - Workflow: resources/workflow.md
         - Platform-level Primitives:
             - Compute: resources/compute.md
             - Depot: resources/depot.md
             - Policy: resources/policy.md

    - Interfaces:
         - Introduction: interfaces.md
         - CLI:
             - Introduction: interfaces/cli.md
             - Installation: interfaces/cli/installation.md
             - Initialization: interfaces/cli/initialization.md
             - Command Reference: interfaces/cli/command_reference.md
         - GUI:
             - Introduction: interfaces/gui.md
             - Atlas: interfaces/gui/atlas.md
             - Audiences: interfaces/gui/audiences.md
             - Bifrost: interfaces/gui/bifrost.md
             - Lens: interfaces/gui/lens.md
             - Metis: interfaces/gui/metis.md
             - Notebook: interfaces/gui/notebook.md
             - Operations: interfaces/gui/operations.md
             - Workbench: interfaces/gui/workbench.md

# to be hidden from the top navigation bar on the webpages
    - Philosophy:
         - About DataOS: philosophy/about_dataos.md
         - Architecture: philosophy/architecture.md
         - Reference: philosophy/reference.md

    - By Role: roles.md
    
    - Glossary: glossary.md