#### DO NOT CHANGE ####
site_name: All things DataOS
copyright: Copyright ⓒ 2024 The Modern Data Company
theme:
    name: material
    custom_dir: overrides
    language: en
    features:
      - navigation.instant 
      - navigation.instant.progress
      - navigation.tracking
      - navigation.footer
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.indexes
      - toc.follow
      - navigation.top
      - content.code.copy
      - content.code.annotate
      - content.tooltips
      - search.suggest
      - search.share
      # - navigation.sections
      # - navigation.expand
      # - content.tabs.link
      # - search.highlighting
      # - toc.integrate
    icon:
      admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/code-square-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
    logo: assets/light-modern-logo.png
    favicon: assets/favicon.png
    logo_link_footer: https://themoderndatacompany.com
    logo_footer: /assets/ModernLogo.png
    font:
        text: Inter
        code: Roboto Mono
    palette:
      - scheme: default
        primary: blue-grey
        accent: blue-grey
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
      - scheme: slate
        primary: grey
        accent: grey
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
plugins:
    - search
    - tags
    # - mkdocs-versioning:
    #     version: v0.2
extra:
  generator: true
  analytics: 
    provider: google
    property: G-ZH4G0HKBQC
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
  annotate:
    json: [.s2]
  social:
    - icon: /assets/facebook.png
      link: https://www.facebook.com/themoderndatacompany
    - icon: /assets/twitter.png
      link: https://twitter.com/TheModernDataCo
    - icon: /assets/linkedin.png
      link: https://www.linkedin.com/company/themoderndatacompany
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.js
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html 
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: false
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist
  - pymdownx.tilde
#  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
      toc_depth: 10
      separator: "-"
  - attr_list
  - md_in_html

#### Update for navigation tabs/options ####      
nav:
  - Home: 
    - index.md
    - Architecture: architecture/index.md
    - Resources:
      - resources/index.md
      - Types:
        - resources/types/index.md
        - Bundle: 
          - resources/bundle/index.md
        - Cluster: 
          - resources/cluster/index.md
        - Compute: 
          - resources/compute/index.md
        - Database: 
          - resources/database/index.md
        - Depot: 
          - resources/depot/index.md
        - Grant:
          - resources/grant/index.md
        - Instance Secret: 
          - resources/instance_secret/index.md
        - Lakehouse: 
          - resources/lakehouse/index.md
        - Lens:
          - resources/lens/index.md
        - Monitor: 
          - resources/monitor/index.md
        - Operator: 
          - resources/operator/index.md
        - Pager: 
          - resources/pager/index.md
        - Policy: 
          - resources/policy/index.md
        - Secret: 
          - resources/secret/index.md
        - Service: 
          - resources/service/index.md
        - Stacks:
          - resources/stacks/index.md
          - Beacon: 
            - resources/stacks/beacon/index.md
          - Benthos: 
            - resources/stacks/benthos/index.md
          - CLI Stack: 
            - resources/stacks/cli_stack/index.md
          - Container: 
            - resources/stacks/container/index.md
          - Data Toolbox: 
            - resources/stacks/data_toolbox/index.md
          - DBT: 
            - resources/stacks/dbt/index.md
          - Flare: 
            - resources/stacks/flare/index.md
          - Scanner: 
            - resources/stacks/scanner/index.md
          - Soda: 
            - resources/stacks/soda/index.md
          - Steampipe: 
            - resources/stacks/steampipe/index.md
        - Worker: 
          - resources/worker/index.md
        - Workflow: 
          - resources/workflow/index.md
      - Characteristics: resources/characteristics.md
      - Configuration: resources/manifest_attributes.md
      - YAML files: resources/yaml_configuration.md       
    - Interfaces:
      - interfaces/index.md
      - Atlas:
        - interfaces/atlas/index.md
      - Audiences: 
        - interfaces/audiences/index.md
      - Bifrost: 
        - interfaces/bifrost/index.md
      - CLI: 
        - interfaces/cli/index.md
      - Lens: 
        - interfaces/lens/index.md
      - Metis: 
        - interfaces/metis/index.md
      - Notebook: 
        - interfaces/notebook/index.md
      - Operations: 
        - interfaces/operations/index.md
      - Superset: 
        - interfaces/superset/index.md
      - Workbench: 
        - interfaces/workbench/index.md
    - SDK: 
      - api_docs/index.md
      - DataOS Python SDK: api_docs/dataos_python_sdk.md
      - DataOS PyFlare SDK: api_docs/dataos_pyflare.md
      - DataOS ScalaFlare SDK: api_docs/dataos_scala_sdk/index.html
      - DataOS Kotlin SDK: api_docs/dataos_kotlin_sdk/index.html
  - Data Product: 
    - products/data_product/index.md
    - Data Product Lifecycle:
      - Design: products/data_product/how_to_guides/design.md
      - Build: products/data_product/how_to_guides/build.md
      - Deploy: products/data_product/how_to_guides/deploy.md
      - Iterate: products/data_product/how_to_guides/manage_and_iterate.md
    - Recipes: 
      - Create Data Product template using Cookiecutter: products/data_product/recipes/cookiecutter.md
      - Deploy Data Product using CI/CD pipeline: products/data_product/recipes/ci_cd.md
    - Templates:
      - Smart Home Data Product: products/data_product/templates/smarthome.md
      - FS Accelerator Data Product: products/data_product/templates/accelerator.md
      - Sales 360 Data Product: products/data_product/templates/sales_360.md
    - Configurations: products/data_product/configuration.md  
  - Glossary: glossary/index.md
  - Videos: videos/index.md