#### DO NOT CHANGE ####
site_name: DataOS Documentation
copyright: Copyright ⓒ 2023 The Modern Data Company
theme:
    name: material
    custom_dir: overrides
    language: en
    features:
        - navigation.footer
        - navigation.indexes
        - navigation.tabs
        - navigation.sections
        - navigation.instant
        - navigation.top
        - navigation.tracking
        - toc.follow
        # - toc.integrate
    logo: assets/dark-logo-modern.png
    favicon: assets/favicon.ico
    font:
        text: Roboto
        code: Roboto Mono
    palette:
      - scheme: default
        primary: white
        accent: white
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
      - scheme: slate
        primary: Blue Gray
        accent: Blue Gray
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
plugins:
    - mermaid2
    - search
    # - mkdocs-versioning:
    #     version: v0.2
extra:
  generator: true
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/themoderndatacompany
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheModernDataCo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/themoderndatacompany
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
#   - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 10
      separator: "-"
  - attr_list
  - md_in_html

#### Update for navigation tabs/options ####      
nav:
    - Home: index.md
    # - Minerva: minerva/index.md
    - Applications:
         - Introduction: GUI/GUI.md
         - Metis:
            - Details:
                - Introduction: GUI/GUI Applications/Metis/Metis.md
                - Features: GUI/GUI Applications/Metis/Metis Features/Metis Features.md
                - Architecture: GUI/GUI Applications/Metis/Architecture/Architecture.md
                - Metis UI: GUI/GUI Applications/Metis/Metis UI/Metis UI.md
         - Lens:
            - Details:
                - Introduction: GUI/GUI Applications/Lens/Lens.md
                - Elements: 
                    - Elements: GUI/GUI Applications/Lens/Elements of Lens/Elements of Lens.md
                    - Entity: GUI/GUI Applications/Lens/Elements of Lens/Entity.md
                    - Fields: GUI/GUI Applications/Lens/Elements of Lens/Fields.md
                    - Dimensions: GUI/GUI Applications/Lens/Elements of Lens/Dimensions.md
                    - Measures: GUI/GUI Applications/Lens/Elements of Lens/Measures.md
                    - Relationships: GUI/GUI Applications/Lens/Elements of Lens/Relationships.md
         - Hera: GUI/GUI Applications/Hera/Hera.md
         - Workbench: GUI/GUI Applications/Workbench/Workbench.md
         - Atlas:
            - Atlas:
                - Introduction: GUI/GUI Applications/Atlas/Atlas.md
                - Dashboard: GUI/GUI Applications/Atlas/Dashboard.md 
                - Queries: GUI/GUI Applications/Atlas/Queries.md
                - Snippets: GUI/GUI Applications/Atlas/Snippets.md
                - Alerts: GUI/GUI Applications/Atlas/Alerts.md
                - Destinations: GUI/GUI Applications/Atlas/Destinations.md
         - Operations: GUI/GUI Applications/Operations/Operations.md
         - Notebook: GUI/GUI Applications/Notebook/Notebook.md
         - Audiences: GUI/GUI Applications/Audiences/Audiences.md
         - Odin: GUI/GUI Applications/Odin/Odin.md
         - Bifrost: GUI/GUI Applications/Bifrost/Bifrost.md


    - CLI:
         - Installation: CLI/CLI.md
         - Command Reference: CLI/CLI Command Reference.md  

    - Primitives:
         - Introduction: Primitives/Primitives.md
         - Cluster-level Primitives:
            - Compute: Primitives/Compute/Compute.md
            - Depot: 
                - Depot: Primitives/Depot/Depot.md
                - Depot Service: Primitives/Depot/Depot Service [WIP].md
            - Policy: Primitives/Policy/Policy.md
         - Workspace-level Primitives:
            - Cluster: Primitives/Cluster/Cluster.md
            - Database: Primitives/Database.md
            - Secret: Primitives/Secret.md
            - Service: Primitives/Service/Service.md
            - Workflow: Primitives/Workflow/Workflow.md

         - Depot Config Templates: 
            - Data Sources:
                - Amazon Redshift: depots/redshift.md
                - Amazon S3: depots/amazons3.md
                - Apache Pulsar: depots/pulsar.md
                - Azur Blob Storage: depots/azureblobfilestorage.md
                - Azure Data Lake Storage Gen2: depots/windowsazurstorageblob.md
                - BigQuery: depots/bigquery.md
                - Elasticsearch: depots/elasticsearch.md
                - File: depots/file.md
                - JDBC: depots/jdbc.md
                - Kafka: depots/kafka.md
                - Microsoft SQL Server: depots/msqlserver.md
                - MYSQL: depots/mysql.md
                - Oracle: depots/oracle.md
                - PostgreSQL: depots/postgresql.md
                - Presto: depots/presto.md
                - Redis: depots/redis.md
                - Snowflake: depots/snowflake.md
                
                
    - Stacks: 
        # - Toolbox: docs/stacks/Toolbox.md
         - Introduction: Stacks/Stacks.md
         - Scanner: Stacks/Scanner/Scanner.md
         - Flare: Stacks/Flare/Flare.md
         - Benthos: Stacks/Benthos/Benthos.md
         - Beacon: Stacks/Beacon/Beacon.md
         - Alpha: Stacks/Alpha.md
         - Airbyte: Stacks/Airbyte/Airbyte.md

         - Scenarios: 
            - Use Cases: 
                - Partitioning: flare/partitioning.md
                - Partition Evolution: flare/partitionevolution.md
                - Data Replay: flare/datareplay.md
                - Merging Small Files: flare/compactingfiles.md
                - Concurrent Writes: flare/concurrent.md
                - GCP Service Account Permissions: flare/gcpsecretpolicy.md
                - Query Dataset for Job in Progress:  flare/queryinjobprogress.md
                - Incremental Data Workload: flare/incremental.md
                - Reading Stream Data: flare/readingstreamdata.md
                
    - Contact:
         - Introduction: governance/datagovernance.md
         - Data Profiling: governance/dataprofile.md
    #     - Metrics and Checks: governance/metricschecks.md
         - Data Fingerprinting: governance/fingerprinting.md
         - Assertions: governance/assertions.md
         - Policies: governance/policies.md

   # - Surge: surge/index.md

   # - Catalog: catalog/index.md
    - Glossary: 
         - Tableau: integrations/tableau.md
         - PowerBI: integrations/powerbi.md
         - IBM SPSS Statistics: integrations/spss.md
   # - Workbench: workbench/index.md


# to be hidden from the top navigation bar on the webpages
    - About DataOS:
         - Introduction: About DataOS/About DataOS.md
         - Architecture: About DataOS/Layered Architecture/Layered Architecture.md
         - Philosophy: About DataOS/DataOS Philosophy & Values [WIP].md
        