#### DO NOT CHANGE ####
site_name: All things DataOS
copyright: Copyright ⓒ 2023 The Modern Data Company
theme:
    name: material
    custom_dir: overrides
    language: en
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.instant
        - navigation.top
        - navigation.tracking
        - content.code.copy
        - content.code.annotate
         - toc.follow
         - toc.integrate
    logo: assets/light-modern-logo.png
    favicon: assets/favicon.png
    logo_link_footer: https://themoderndatacompany.com
    logo_footer: /assets/ModernLogo.png
    font:
        text: Inter
        code: Roboto Mono
    palette:
      - scheme: default
        primary: blue-grey
        accent: blue-grey
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
      - scheme: slate
        primary: grey
        accent: grey
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
plugins:
    - search
    # - mkdocs-versioning:
    #     version: v0.2
extra:
  generator: true
  # section added by Manish
  analytics: 
    provider: google
    property: G-ZH4G0HKBQC
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
  # end of the section added by Manish
  annotate:
    json: [.s2]
  social:
    - icon: /assets/facebook.png
      link: https://www.facebook.com/themoderndatacompany
    - icon: /assets/twitter.png
      link: https://twitter.com/TheModernDataCo
    - icon: /assets/linkedin.png
      link: https://www.linkedin.com/company/themoderndatacompany
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.js
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
#   - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 10
      separator: "-"
  - attr_list
  - md_in_html

#### Update for navigation tabs/options ####      
nav:
    - Home: index.md

    - Resources:
         - Overview: resources.md
         - Bundle: resources/bundle.md
         - Cluster: resources/cluster.md
         - Compute: resources/compute.md
         - Depot: resources/depot.md
         - Lakehouse: resources/lakehouse.md
         - Operator: resources/operator.md
         - Policy: resources/policy.md
         - Secret: resources/secret.md
         - Service: resources/service.md 
         - Worker: resources/worker.md
         - Workflow: resources/workflow.md  
         - Stacks:
              - Introduction: resources/stacks.md
              - Alpha: resources/stacks/alpha.md
              - Beacon: resources/stacks/beacon.md
              - Benthos: resources/stacks/benthos.md
              - CLI: resources/stacks/cli.md
              - Data Toolbox: resources/stacks/data_toolbox.md
              - Flare: resources/stacks/flare.md
              - Scanner: resources/stacks/scanner.md
              - Soda: resources/stacks/soda.md
              - Steampipe: resources/stacks/steampipe.md

                 
    - Interfaces:
         - Overview: interfaces.md
         - Atlas: interfaces/atlas.md
         - Audiences: interfaces/audiences.md
         - Bifrost: interfaces/bifrost.md
         - CLI: interfaces/cli.md
         - Lens: interfaces/lens.md
         - Metis: interfaces/metis.md
         - Notebook: interfaces/notebook.md
         - Operations: interfaces/operations.md
         - Workbench: interfaces/workbench.md        

# to be hidden from the top navigation bar on the webpages
    - Architecture: architecture.md
    
    - Glossary: glossary.md
    - Videos: videos.md