#### DO NOT CHANGE ####
site_name: DataOS Documentation 
copyright: Copyright ⓒ 2024 The Modern Data Company
theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.instant 
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - navigation.top

    # - navigation.sections
    # - navigation.expand
    - content.code.copy
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    - search.suggest
    # - search.highlighting
    - search.share
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/code-square-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: assets/light-modern-logo.png
  favicon: assets/favicon.png
  logo_link_footer: https://themoderndatacompany.com
  logo_footer: /assets/ModernLogo.png
  font:
      text: Inter
      code: Roboto Mono
  palette:
    - scheme: default
      primary: blue-grey
      accent: blue-grey
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
plugins:
    - search
    - tags
    # - mkdocs-versioning:
    #     version: v0.2
extra:
  generator: true
  analytics: 
    provider: google
    property: G-ZH4G0HKBQC
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
  annotate:
    json: [.s2]
  social:
    - icon: /assets/facebook.png
      link: https://www.facebook.com/themoderndatacompany
    - icon: /assets/twitter.png
      link: https://twitter.com/TheModernDataCo
    - icon: /assets/linkedin.png
      link: https://www.linkedin.com/company/themoderndatacompany
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.js
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html 
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: false
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist
  - pymdownx.tilde
#  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
      toc_depth: 10
      separator: "-"
  - attr_list
  - md_in_html

#### Update for navigation tabs/options ####      
nav:
  - Home: 
    - Home: index.md
    - Architecture: architecture/index.md
    - Products: 
      - products/index.md
      - 'Data Product':
        - products/data_product/index.md
        - 'How to':
          - products/data_product/how_to_guides/index.md
          - 'Design': products/data_product/how_to_guides/design.md
          - 'Build': products/data_product/how_to_guides/build.md
          - 'Deploy': products/data_product/how_to_guides/deploy.md
          - 'Manage and Iterate': products/data_product/how_to_guides/manage_and_iterate.md
        - 'Recipes': 
          - 'Create Data Product template using Cookiecutter': products/data_product/recipes/cookiecutter.md
          - 'Deploy Data Product using CI/CD pipeline': products/data_product/recipes/ci_cd.md
    - Resources:
      - resources/index.md
      - Bundle: 
        - resources/bundle/index.md
        - 'Quick Start': resources/bundle/quick_start_guide.md
        - 'How to Guide':
          - resources/bundle/how_to_guide/index.md
        - 'Reference': resources/bundle/reference.md
        - 'Explanation': resources/bundle/explanation.md
      - Cluster: 
        - resources/cluster/index.md
        - 'Quick Start': resources/cluster/quick_start_guide.md
        - 'How to Guide':
          - resources/cluster/how_to_guide/index.md
        - 'Reference': resources/cluster/reference.md
        - 'Explanation': resources/cluster/explanation.md
      - Compute: 
        - resources/compute/index.md
        - 'Quick Start': resources/compute/quick_start_guide.md
        - 'How to Guide':
          - resources/compute/how_to_guide/index.md
        - 'Reference': resources/compute/reference.md
        - 'Explanation': resources/compute/explanation.md
      - Database: 
        - resources/database/index.md
        - 'Quick Start': resources/database/quick_start_guide.md
        - 'How to Guide':
          - resources/database/how_to_guide/index.md
        - 'Reference': resources/database/reference.md
        - 'Explanation': resources/database/explanation.md
      - Depot: 
        - resources/depot/index.md
        - 'Quick Start': resources/depot/quick_start_guide.md
        - 'How to Guide':
          - resources/depot/how_to_guide/index.md
        - 'Reference': resources/depot/reference.md
        - 'Explanation': resources/depot/explanation.md
      - Grant: 
        - resources/grant/index.md
        - 'Quick Start': resources/grant/quick_start_guide.md
        - 'How to Guide':
          - resources/grant/how_to_guide/index.md
        - 'Reference': resources/grant/reference.md
        - 'Explanation': resources/grant/explanation.md
      - 'Instance Secret': 
        - resources/instance_secret/index.md
        - 'First Steps': resources/instance_secret/first_steps.md
        - 'Configurations': resources/instance_secret/configuration.md
      - Lakehouse: 
        - resources/lakehouse/index.md
        - 'Quick Start': resources/lakehouse/quick_start_guide.md
        - 'How to Guide':
          - resources/lakehouse/how_to_guide/index.md
        - 'Reference': resources/lakehouse/reference.md
        - 'Explanation': resources/lakehouse/explanation.md
      - Lens: 
        - resources/lens/index.md
        - 'Quick Start': resources/lens/quick_start_guide.md
        - 'How to Guide':
          - resources/lens/how_to_guide/index.md
        - 'Reference': resources/lens/reference.md
        - 'Explanation': resources/lens/explanation.md
      - Monitor: 
        - resources/monitor/index.md
        - 'Quick Start': resources/monitor/quick_start_guide.md
        - 'How to Guide':
          - resources/monitor/how_to_guide/index.md
          - 'Monitor Cluster Memory Usage': resources/monitor/how_to_guide/monitor_cluster_memory_usage.md
          - 'Monitor Prometheus': resources/monitor/how_to_guide/monitor_prometheus.md
          - 'Monitor Profile Checks': resources/monitor/how_to_guide/monitor_profile_checks.md
        - 'Reference': resources/monitor/reference.md
        - 'Explanation': resources/monitor/explanation.md
      - Operator: 
        - resources/operator/index.md
        - 'Quick Start': resources/operator/quick_start_guide.md
        - 'How to Guide':
          - resources/operator/how_to_guide/index.md
        - 'Reference': resources/operator/reference.md
        - 'Explanation': resources/operator/explanation.md
      - Pager: 
        - resources/pager/index.md
        - 'Quick Start': resources/pager/quick_start_guide.md
        - 'How to Guide':
          - resources/pager/how_to_guide/index.md
        - 'Reference': resources/pager/reference.md
        - 'Explanation': resources/pager/explanation.md
      - Policy: 
        - resources/policy/index.md
        - 'Quick Start': resources/policy/quick_start_guide.md
        - 'How to Guide':
          - resources/policy/how_to_guide/index.md
        - 'Reference': resources/policy/reference.md
        - 'Explanation': resources/policy/explanation.md
      - Secret: 
        - resources/secret/index.md
        - 'First Steps': resources/secret/first_steps.md
        - 'Configurations': resources/secret/configuration.md        
        - 'How to Guide':
          - resources/secret/how_to_guide/recipe1.md
          - resources/secret/how_to_guide/recipe2.md
      - Service: 
        - resources/service/index.md
        - 'Quick Start': resources/service/quick_start_guide.md
        - 'How to Guide':
          - resources/service/how_to_guide/recipes.md
        - 'Reference': resources/service/reference.md
        - 'Explanation': resources/service/explanation.md
      - Stack: 
        - resources/lakehouse/index.md
        - 'Quick Start': resources/lakehouse/quick_start_guide.md
        - 'How to Guide':
          - resources/lakehouse/how_to_guide/index.md
        - 'Reference': resources/lakehouse/reference.md
        - 'Explanation': resources/lakehouse/explanation.md
      - Volume: 
        - resources/volume/index.md
        - 'Getting started': resources/volume/getting_started.md
        - 'How to Guide':
          - resources/volume/how_to_guide/index.md
        - 'Configuration': resources/volume/configuration.md
      - Worker: 
        - resources/worker/index.md
        - 'First Steps': resources/worker/first_steps.md
        - 'Recipes':
          - 'Autoscale Workers': resources/worker/how_to_guide/autoscale_workers.md
          - 'Referring Secrets': resources/worker/how_to_guide/referring_secrets_in_worker.md
          - 'Transform stream data': resources/worker/how_to_guide/transforming_stream_data.md
          - 'Sync data from Fastbase to Icebase': resources/worker/how_to_guide/transforming_stream_data.md
        - 'Configuration': resources/worker/configuration.md
        - 'Core Concepts': resources/worker/core_concepts.md
      - Workflow: 
        - resources/workflow/index.md
        - 'Quick Start': resources/workflow/quick_start_guide.md
        - 'How to Guide':
          - resources/workflow/how_to_guide/index.md
        - 'Configuration': resources/workflow/reference.md
        - 'Explanation': resources/workflow/explanation.md
    - Interfaces:
      - interfaces/index.md
      - 'Data Product Hub': 
        - interfaces/data_product_hub/index.md
        - 'Quick Start': interfaces/data_product_hub/quick_start_guide.md
        - 'Explanation': interfaces/data_product_hub/explanation.md
        - 'Reference': interfaces/data_product_hub/reference.md
      - 'Atlas': 
        - interfaces/data_product_hub/index.md
        - 'Quick Start': interfaces/atlas/quick_start_guide.md
        - 'Explanation': interfaces/atlas/explanation.md
        - 'Reference': interfaces/atlas/reference.md
      - Audiences: interfaces/index.md
      - Bifrost: interfaces/index.md
      - CLI: interfaces/index.md
      - Lens: interfaces/index.md
      - Metis: interfaces/index.md
      - Notebook: interfaces/index.md
      - Operations: interfaces/index.md
      - Superset: interfaces/index.md
      - Workbench: interfaces/index.md
  - 'Getting started': 
    - 'Getting Started': getting_started/index.md
    - 'Installation': getting_started/installation.md
    - 'Connect to data source': getting_started/connect_to_data_source.md
    - 'Scan metadata': getting_started/scan_metadata.md
    - 'Run ETL job': getting_started/run_etl_job.md
  - Appendix: appendix.md
  - Glossary: glossary.md

#   - Concepts: 
#     - Resources:
#       - Overview: resources.md
#       - Bundle: resources/bundle.md
#       - Cluster: resources/cluster.md
#       - Compute: resources/compute.md
#       - Database: resources/database.md
#       - Depot: resources/depot.md
#       - 'Instance Secret': resources/instance_secret.md 
#       - Lakehouse: resources/lakehouse.md
#       - Monitor: resources/monitor.md
#       - Operator: resources/operator.md
#       - Pager: resources/pager.md
#       - Policy: resources/policy.md
#       - Secret: resources/secret.md
#       - Service: resources/service.md 
#       - Worker: resources/worker.md
#       - Workflow: resources/workflow.md 
#       - Stacks:
#         - Introduction: resources/stacks.md
#         - Alpha: resources/stacks/alpha.md
#         - Beacon: resources/stacks/beacon.md
#         - Benthos: resources/stacks/benthos.md
#         - 'CLI Stack': resources/stacks/cli_stack.md
#         - Data Toolbox: resources/stacks/data_toolbox.md
#         - Flare: resources/stacks/flare.md
#         - Scanner: resources/stacks/scanner.md
#         - Soda: resources/stacks/soda.md
#         - Steampipe: resources/stacks/steampipe.md

                 
#     - Interfaces:
#         - Overview: interfaces.md
#         - Atlas: interfaces/atlas.md
#         - Audiences: interfaces/audiences.md
#         - Bifrost: interfaces/bifrost.md
#         - CLI: interfaces/cli.md
#         - Lens: interfaces/lens.md
#         - Metis: interfaces/metis.md
#         - Notebook: interfaces/notebook.md
#         - Operations: interfaces/operations.md
#         - Superset: interfaces/superset.md
#         - Workbench: interfaces/workbench.md 
#     - Architecture: architecture.md
#     - Glossary: glossary.md
#     - Videos: videos.md
# #     - Tutorials:
# #     - Guides:
# #     - API:
#     # - Reference: 


       

# # to be hidden from the top navigation bar on the webpages
