#### DO NOT CHANGE ####
site_name: All things DataOS
copyright: Copyright ⓒ 2024 The Modern Data Company
theme:
    name: material
    custom_dir: overrides
    language: en
    features:
      - navigation.instant 
      - navigation.instant.progress
      - navigation.tracking
      - navigation.footer
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.indexes
      - toc.follow
      - navigation.top
      - content.code.copy
      - content.code.annotate
      - content.tooltips
      - search.suggest
      - search.share
      # - navigation.sections
      # - navigation.expand
      # - content.tabs.link
      # - search.highlighting
      # - toc.integrate
    icon:
      admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/code-square-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
    logo: assets/light-modern-logo.png
    favicon: assets/favicon.png
    logo_link_footer: https://themoderndatacompany.com
    logo_footer: /assets/ModernLogo.png
    font:
        text: Inter
        code: Roboto Mono
    palette:
      - scheme: default
        primary: blue-grey
        accent: blue-grey
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
      - scheme: slate
        primary: grey
        accent: grey
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
plugins:
    - search
    - tags:
        enabled: true
        tags: false
extra:
  generator: true
  analytics: 
    provider: google
    property: G-ZH4G0HKBQC
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
  annotate:
    json: [.s2]
  social:
    - icon: /assets/facebook.png
      link: https://www.facebook.com/themoderndatacompany
    - icon: /assets/twitter.png
      link: https://twitter.com/TheModernDataCo
    - icon: /assets/linkedin.png
      link: https://www.linkedin.com/company/themoderndatacompany
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.js
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html 
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: false
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist
  - pymdownx.tilde
#  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
      toc_depth: 10
      separator: "-"
  - attr_list
  - md_in_html

#### Update for navigation tabs/options ####      
nav:
  - Home: 
    - index.md
    - Philosophy: philosophy/index.md
    - Architecture: architecture/index.md
    - Interfaces:
      - interfaces/index.md
      - Atlas: 
        - interfaces/atlas/index.md
        - Dashboards: 
          - interfaces/atlas/dashboards/index.md
          - Adding Visualizations to Dashboard: interfaces/atlas/dashboards/adding_visualizations/index.md
        - Queries: interfaces/atlas/queries.md
        - Snippet: interfaces/atlas/snippet.md
        - Alerts: interfaces/atlas/alerts.md
        - Destinations: interfaces/atlas/destinations.md
        - Integration: 
          - interfaces/atlas/bi_tools/index.md
          - Power BI: 
            - interfaces/atlas/bi_tools/powerbi/index.md
            - Using Connector: interfaces/atlas/bi_tools/powerbi/powerbi_custom_connector.md
            - Using ODBC Driver: interfaces/atlas/bi_tools/powerbi/power_bi.md
          - Tableau: interfaces/atlas/bi_tools/tableau/index.md
          - IBM SPSS: interfaces/atlas/bi_tools/spss/index.md
      - Audiences: 
        - interfaces/audiences/index.md
        - Audiences UI: interfaces/audiences/audiences_ui/index.md
        - Getting Started: interfaces/audiences/getting_started/index.md
      - Bifrost: 
        - interfaces/bifrost/index.md
        - ABAC Implementation: interfaces/bifrost/abac_implementation_in_dataos.md
        - User: interfaces/bifrost/users.md
        - Use-cases: interfaces/bifrost/use_cases.md
        - Grant: interfaces/bifrost/grants.md
        - Role: interfaces/bifrost/roles.md
        - Grant Requests: interfaces/bifrost/grant_requests.md
        - Heimdall Primitives: interfaces/bifrost/heimdall_primitives.md
      - CLI: 
        - interfaces/cli/index.md
        - Installation: interfaces/cli/installation.md
        - Initialization: interfaces/cli/initialization.md
        - Command Reference: interfaces/cli/command_reference.md
      - Data Product Hub: 
        - interfaces/data_product_hub/index.md
        - Data Products: interfaces/data_product_hub/tabs/data_product_tab.md
        - Recent Updates: interfaces/data_product_hub/tabs/recent_updates.md
        - About: interfaces/data_product_hub/tabs/about.md
      - Lens: 
        - interfaces/lens/index.md
        - Building Lens: 
          - interfaces/lens/building_lens/index.md
          - Tutorial: interfaces/lens/building_lens/tutorial_lens.md
          - Data Modelling Concepts: interfaces/lens/building_lens/data_modeling_concepts.md
          - Lens Attributes: interfaces/lens/building_lens/attributes_lens.md
          - Dynamic Parameters: interfaces/lens/building_lens/scenarios_dynamic_params.md
        - Lens Explorer: interfaces/lens/lens_explorer/index.md
        - Lens Ecosystem: 
          - interfaces/lens/lens_ecosystem/index.md
          - Lens Query: interfaces/lens/lens_ecosystem/lens_query.md
        - Elements of Lens: 
          - interfaces/lens/elements_of_lens/index.md
          - Entities: interfaces/lens/elements_of_lens/entity.md
          - Fields: interfaces/lens/elements_of_lens/fields.md
          - Dimensions: interfaces/lens/elements_of_lens/dimensions.md
          - Measures: interfaces/lens/elements_of_lens/measures.md
          - Relationships: interfaces/lens/elements_of_lens/relationships.md
      - Metis: 
        - interfaces/metis/index.md
        - Metis UI: 
          - interfaces/metis/navigating_metis_ui_how_to_guide/index.md
          - Pre-defined Roles and Policies: interfaces/metis/navigating_metis_ui_how_to_guide/pre_defined_roles_and_policies.md
        - Key Features: interfaces/metis/metis_features.md
        - Metadata of Products: 
          - interfaces/metis/metis_ui_products/index.md
          - Metadata of Data Products: interfaces/metis/metis_ui_products/metis_products_data_products.md
        - Metadata of Data Assets: 
          - interfaces/metis/metis_ui_assets/index.md
          - Metadata of Tables: interfaces/metis/metis_ui_assets/metis_assets_tables.md
          - Metadata of Topics: interfaces/metis/metis_ui_assets/metis_assets_topic.md
          - Metadata of Dashboards: interfaces/metis/metis_ui_assets/metis_assets_dashboards.md
        - Metadata of Resources: 
          - interfaces/metis/metis_ui_resources/index.md
          - Bundles: interfaces/metis/metis_ui_resources/metis_resources_bundles.md
          - Clusters: interfaces/metis/metis_ui_resources/metis_resources_clusters.md
          - Computes: interfaces/metis/metis_ui_resources/metis_resources_computes.md
          - Databases: interfaces/metis/metis_ui_resources/metis_resources_databases.md
          - Depots: interfaces/metis/metis_ui_resources/metis_resources_depots.md
          - Instance Secret: interfaces/metis/metis_ui_resources/metis_resources_instance_secrets.md
          - Lakehouses: interfaces/metis/metis_ui_resources/metis_resources_lakehouses.md
          - Monitors: interfaces/metis/metis_ui_resources/metis_resources_monitors.md
          - Operators: interfaces/metis/metis_ui_resources/metis_resources_operators.md
          - Pagers: interfaces/metis/metis_ui_resources/metis_resources_pagers.md
          - Policies: interfaces/metis/metis_ui_resources/metis_resources_policies.md
          - Secrets: interfaces/metis/metis_ui_resources/metis_resources_secrets.md
          - Services: interfaces/metis/metis_ui_resources/metis_resources_services.md
          - Stacks: interfaces/metis/metis_ui_resources/metis_resources_stacks.md
          - Workers: interfaces/metis/metis_ui_resources/metis_resources_workers.md
          - Workflows: interfaces/metis/metis_ui_resources/metis_resources_workflows.md
      - Notebook: 
        - interfaces/notebook/index.md
      - Operations: 
        - interfaces/operations/index.md
      # - Superset: 
      #   - interfaces/superset/index.md
      - Workbench: 
        - interfaces/workbench/index.md      
    - Resources:
      - resources/index.md
      - Types:
        - resources/types/index.md
        - Bundle: 
          - resources/bundle/index.md
        - Cluster: 
          - resources/cluster/index.md
        - Compute: 
          - resources/compute/index.md
        - Database: 
          - resources/database/index.md
        - Depot: 
          - resources/depot/index.md
        - Grant:
          - resources/grant/index.md
        - Instance Secret: 
          - resources/instance_secret/index.md
        - Lakehouse: 
          - resources/lakehouse/index.md
        # - Lens:
        #   - resources/lens/index.md
        - Monitor: 
          - resources/monitor/index.md
        - Operator: 
          - resources/operator/index.md
        - Pager: 
          - resources/pager/index.md
        - Policy: 
          - resources/policy/index.md
        - Secret: 
          - resources/secret/index.md
        - Service: 
          - resources/service/index.md
        - Stacks:
          - resources/stacks/index.md
          - Beacon: 
            - resources/stacks/beacon/index.md
          - Benthos: 
            - resources/stacks/benthos/index.md
          - CLI Stack: 
            - resources/stacks/cli_stack/index.md
          - Container: 
            - resources/stacks/container/index.md
          - Data Toolbox: 
            - resources/stacks/data_toolbox/index.md
          - DBT: 
            - resources/stacks/dbt/index.md
          - Flare: 
            - resources/stacks/flare/index.md
          - Scanner: 
            - resources/stacks/scanner/index.md
          - Soda: 
            - resources/stacks/soda/index.md
          - Steampipe: 
            - resources/stacks/steampipe/index.md
        - Volume: 
          - resources/volume/index.md
        - Worker: 
          - resources/worker/index.md
          - First Steps: resources/worker/first_steps.md
          - Configuration: resources/worker/configuration.md
        - Workflow: 
          - resources/workflow/index.md
      - Characteristics: resources/characteristics.md
      - Configuration: resources/manifest_attributes.md
      - YAML files: resources/yaml_configuration.md
    - SDK: 
      - api_docs/index.md
      - DataOS Python SDK: api_docs/dataos_python_sdk.md
      - DataOS PyFlare SDK: api_docs/dataos_pyflare.md
      - DataOS Flare SDK: api_docs/dataos_scala_sdk/index.html
      - DataOS Kotlin SDK: api_docs/dataos_kotlin_sdk/index.html
  - Getting Started: 
    - getting_started/index.md
    - Data Product Consumer: getting_started/data_product_consumer/index.md
    - Data Product Developer: getting_started/data_product_developer/index.md
    # - Data Product Owner: getting_started/data_product_owner/index.md
    - Operator: getting_started/operator/index.md
  - Data Product: 
    - products/data_product/index.md
    - Data Product Life-cycle:
      - products/data_product/how_to_guides/index.md
      - Design: products/data_product/how_to_guides/design.md
      - Build: products/data_product/how_to_guides/build.md
      - Deploy: products/data_product/how_to_guides/deploy.md
      - Iterate: products/data_product/how_to_guides/iterate.md
    - Recipes: 
      - Create Data Product template using Cookiecutter: products/data_product/recipes/cookiecutter.md
      - Deploy Data Product using CI/CD pipeline: products/data_product/recipes/ci_cd.md
    - Examples:
      - FS Accelerator Data Product: products/data_product/templates/accelerator.md
      - Sales 360 Data Product : products/data_product/templates/sales_360.md
    - Configurations: products/data_product/configuration.md   
    - Core Concepts: products/data_product/core_concepts.md
  - Glossary: glossary/index.md
  - Videos: videos/index.md