image: atlassian/default-image:2

pipelines:
  tags:
    '*[0-9].*[0-9].*[0-9]-*':
      - step:
          name: dev-release
          image: atlassian/default-image:2
          deployment: staging
          clone:
            enabled: true
          services:
            - docker
          size: 2x
          caches:
            - maven
            - gradle
            - docker
          script:
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - VERSION=${BITBUCKET_TAG}
            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build 	--build-arg GIT_VERSION=${BITBUCKET_COMMIT} --build-arg BUILD_DATE=${BUILD_DATE} -f ./docker/Dockerfile -t rubiklabs/modern-docs:${BITBUCKET_TAG} .
            # push the new Docker image to the Docker registry
            - docker push rubiklabs/modern-docs:${BITBUCKET_TAG}
    '*[0-9].*[0-9].*[0-9]':
      - step:
          name: public-release
          image: atlassian/default-image:2
          deployment: production
          clone:
            enabled: true
          services:
            - docker
          size: 2x
          caches:
            - maven
            - gradle
            - docker
          script:
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - VERSION=${BITBUCKET_TAG}
            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build --build-arg GIT_VERSION=${BITBUCKET_COMMIT} --build-arg BUILD_DATE=${BUILD_DATE} -f ./docker/Dockerfile -t rubiklabs/modern-docs:${BITBUCKET_TAG} .
            # push the new Docker image to the Docker registry
            - docker push rubiklabs/modern-docs:${BITBUCKET_TAG}
definitions:
  services:
    docker:
      memory: 4096
