version: v1
name: productdb
type: depot
layer: user
depot:
  type: JDBC                                # Depot type
  description: To write data to retaildb postgresql database
  external: true
  connectionSecret:                               # Data source specific configurations
    - acl: rw
      type: key-value-properties
      data:
        username: "postgres"
        password: "XXXXa1110XXb540Xad2fXe2245X90aXXX"
  spec:                                           # Data source specific configurations
    database: product
    host: usr-db-dataos-ck-vgji-colorfuldo-dev.postgres.database.azure.com
    port: 5432
    subprotocol: postgresql