version: v1
name: {workflow-name}
type: workflow
workflow:
  dag:
    - name: ${alpha-wf-mail-alert}
      spec:
        resources:
          requests:
            cpu: 250m
            memory: 500m
          limits:
            cpu: 1
            memory: 1Gi
        dataosSecrets:           # Referencing the Secret
          - name: ${secret-name}
            workspace: public
            keys:
              - ${API_KEY}
              - ${DATAOS_API_TOKEN}
              - ${DATAOS_ENV_LINK}
              - ${DATAOS_PULSAR_TOPIC_SUB_ID}

        stack: ${stack-name}
        compute: runnable-default
        stackSpec:
          image: rubiklabs/workflow_lobos_mail_alert:1.0
          imagePullSecret: modern-docker-secret
          command:
            - python
          arguments:
            - -u
            - ./email_alert_script.py
