  version: v1
  name: customers-test1          
  type: service
  service:
    replicas: 1
    ingress:
      enabled: true
      stripPath: true
      path: /customersdb/api/v1    # naming of path what you want but formatting is neccessary.          
      noAuthentication: true
    stack: beacon+rest
    compute: runnable-default
    envs:
      PGRST_OPENAPI_SERVER_PROXY_URI: https://emerging-hawk.dataos.app/customersdb/api/v1

    stackSpec:
      source:
        type: database
        name: customersdb              
        workspace: public
    topology:
      - name: database
        type: input
        doc: customers database connection
      - name: rest-api
        type: output
        doc: serves up the customers database as a RESTful API
        dependencies:
          - database
