name: sales-search
version: v1
type: service
tags:
  - service
  - dataos:type:resource
  - dataos:resource:service
  - dataos:layer:user
description: Lakesearch Service
workspace: public
service:
  servicePort: 4080
  ingress:
    enabled: true
    stripPath: false
    path: /lakesearch/public:sales-search
    noAuthentication: true
  replicas: 1
  logLevel: DEBUG
  compute: runnable-default
  envs:
    LAKESEARCH_SERVER_NAME: public:sales-search
    LAKESEARCH_SERVER_VERSION: 0
    LAKESEARCH_DATA_PATH: /var/dataos/persistent_data/sales-search/data 
  persistentVolume:
    name: lakesearch-pv-claim
    directory: sales-search
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  stack: lakesearch:1.0
  stackSpec:
    lakesearch:
      tables:
        - dataset: dataos://icebase:audience/customers_large_data
          name: customers_large_data

          options: 
            batch: 1000
            sync_interval: 20s
            shards: 3
            region: ap-south-1
          
          strict: false

          sort:
              name: customer_id
          
          settings:
            analysis:
              analyzer:
                default:
                  type: standard





